### ISSUE TITLE
Asset pipeline to _content markdown files

### ISSUE THREAD

**Issue by cunning-folk** [gblakeman/yassss#2] opened 2019-12-18 16:11 UTC
@gblakeman 

Any idea why the code 

`![Cliff]({% asset cliff.jpg @path %})`

will render the image to a 'post' but not to markdown files contained in '_content' (about, contact, home, etc)?

🤯

**Comment by gblakeman** [comment] 2019-12-18 18:29
Ah, sorry. Because `_content` skips the Liquid processor by default. I created the `_content` convention for Yassss. It was intended to be used for small buckets of Markdown text content rather than full pages of content.

BUT, try adding `.liquid` to the end of a file (`_content/something.md.liquid`). I _think_ it might bring it through the Liquid processor that way. If it doesn’t, let me know and I’ll see if there's a quick patch to get it to work one way or another. It’s definitely something Yassss should support in the future.

**Comment by cunning-folk** [comment] 2019-12-19 00:54
@gblakeman 

adding .liquid to the .md file doesnt seem to work and throws yarn error
`Liquid Exception: No such file or directory @ rb_sysopen - /Users/petermcewen/Sites/blog/_content/about.md in about/index.html`

Workaround for now is to create a [permalink](https://jekyllrb.com/docs/permalinks/)for /about/. The permalink renders the image using `![Image Caption]({% asset image.jpg @path %})`

cheers

**Comment by gblakeman** [comment] 2019-12-19 02:24
I’ve updated the way I do parsing with the `{{ content }}` tags so that it can now access the `{% asset %}` tag. Fixed in #3.

**Closed** 2019-12-19 02:24 UTC
